# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-03 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180803_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(max_length=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upwd',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
    ]
