# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-26 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180726_0949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
