# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Googs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spec', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='static/upload')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='static/upload')),
                ('desc', models.TextField()),
            ],
        ),
    ]
