# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_googs_googstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googs',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goods'),
        ),
        migrations.AlterField(
            model_name='googstype',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goodstype'),
        ),
    ]
